twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
        tinymce_api_key: '%env(TINYMCE_API_KEY)%'

when@test:
    twig:
        strict_variables: true
