apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: cv-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      securityContext:
        fsGroup: 82
      initContainers:
        - name: init-uploads-perms
          image: busybox:1.36
          command: ["sh", "-lc"]
          args:
            - |
              mkdir -p /var/www/html/public/uploads
              chown -R 82:82 /var/www/html/public/uploads
              chmod -R 775 /var/www/html/public/uploads
          volumeMounts:
            - name: uploads
              mountPath: /var/www/html/public/uploads
      containers:
        - name: php
          image: ghcr.io/norrim/my-cv-php:prod
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: cv-secrets
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: uploads
              mountPath: /var/www/html/public/uploads
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads
---
apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: cv-prod
spec:
  selector:
    app: php
  ports:
    - port: 9000
      targetPort: 9000
