apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cv
  namespace: cv-prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - remitiertant.fr
        - www.remitiertant.fr
      secretName: cv-tls
  rules:
    - host: remitiertant.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
    - host: www.remitiertant.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
